
######################### feature Common Configurations #############################
# slot 唯一标识码
# feature_group 特征的field
# feature_type 特征的类型，1: 用户特征  2: 物品特征  3: 上下文特征
# value_type 特征的数据类型， 2: 字符型  3: 连续值（线性增幅）  4: 连续值（指数型增幅） 5: 字符数组  6: 字符有序数组 7: 时间戳型
- slot: 1
  feature_group: 1
  feature_type: 2
  feature_name: d_st_2_did
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 2
  feature_group: 2
  feature_type: 2
  feature_name: d_st_7_copyrightid
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 3
  feature_group: 3
  feature_type: 2
  feature_name: d_st_2_app
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 4
  feature_group: 4
  feature_type: 2
  feature_name: d_st_7_firstcategoryid
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 5
  feature_group: 5
  feature_type: 2
  feature_name: d_st_7_secondcategoryid
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 6
  feature_group: 6
  feature_type: 2
  feature_name: d_st_7_thirdcategoryid
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 7
  feature_group: 7
  feature_type: 2
  feature_name: d_st_2_cpbookid
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 8
  feature_group: 8
  feature_type: 2
  feature_name: d_st_2_title
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 9
  feature_group: 9
  feature_type: 2
  feature_name: d_st_2_author
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 10
  feature_group: 10
  feature_type: 2
  feature_name: d_st_2_description
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 11
  feature_group: 11
  feature_type: 2
  feature_name: d_st_7_wordcount
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 12
  feature_group: 12
  feature_type: 2
  feature_name: d_st_3_endstatus
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 13
  feature_group: 13
  feature_type: 2
  feature_name: d_st_3_lengthstatus
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 14
  feature_group: 14
  feature_type: 2
  feature_name: d_st_3_status
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 15
  feature_group: 15
  feature_type: 2
  feature_name: d_st_3_salechapterno
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 16
  feature_group: 16
  feature_type: 2
  feature_name: d_st_3_saleprice
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 17
  feature_group: 17
  feature_type: 2
  feature_name: d_st_2_cptitle
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 18
  feature_group: 18
  feature_type: 2
  feature_name: d_st_3_chapterwords
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 19
  feature_group: 19
  feature_type: 2
  feature_name: d_st_7_readnum
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 20
  feature_group: 20
  feature_type: 2
  feature_name: d_st_7_likenum
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 21
  feature_group: 21
  feature_type: 2
  feature_name: d_st_7_hotnum
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 22
  feature_group: 22
  feature_type: 2
  feature_name: d_st_7_adjustnum
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 23
  feature_group: 23
  feature_type: 2
  feature_name: d_st_7_updatedat
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 24
  feature_group: 24
  feature_type: 2
  feature_name: d_dy_4_recvalidshow
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 25
  feature_group: 25
  feature_type: 2
  feature_name: d_dy_4_recread
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 26
  feature_group: 26
  feature_type: 2
  feature_name: d_dy_4_recreadlong
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 27
  feature_group: 27
  feature_type: 2
  feature_name: d_dy_4_recclick
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 28
  feature_group: 28
  feature_type: 2
  feature_name: d_dy_4_recshelf
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 29
  feature_group: 29
  feature_type: 2
  feature_name: d_dy_4_recshare
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 30
  feature_group: 30
  feature_type: 2
  feature_name: d_dy_3_recclickrate
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

- slot: 31
  feature_group: 31
  feature_type: 2
  feature_name: d_dy_3_recavgreadlong
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1

#- slot: 32
#  feature_group: 32
#  feature_type: 1
#  feature_name: u_st_2_uid
#  value_type: 2
#  disperse_num: 0
#  value_max: 0
#  value_min: 0
#  decribe: 用户id
#  status: 1
#  is_dump: 1
- slot: 33
  feature_group: 33
  feature_type: 1
  feature_name: u_st_7_regtime
  value_type: 7
  disperse_num: 10
  value_max: 5184000
  value_min: 86400
  decribe: 用户注册时间,范围 1天 - 60天
  status: 1
  is_dump: 1
- slot: 34
  feature_group: 34
  feature_type: 1
  feature_name: u_st_2_sex
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 性别
  status: 1
  is_dump: 1
- slot: 35
  feature_group: 35
  feature_type: 1
  feature_name: u_st_2_channel
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 年龄
  status: 1
  is_dump: 1
- slot: 36
  feature_group: 36
  feature_type: 1
  feature_name: u_st_2_phone_brand
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1
- slot: 37
  feature_group: 37
  feature_type: 1
  feature_name: u_st_2_city
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 38
  feature_group: 38
  feature_type: 1
  feature_name: c_2_hour
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 39
  feature_group: 39
  feature_type: 1
  feature_name: c_2_timedur
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 40
  feature_group: 40
  feature_type: 1
  feature_name: c_2_weekday
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 41
  feature_group: 41
  feature_type: 3
  feature_name: c_2_pageposition
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 42
  feature_group: 42
  feature_type: 3
  feature_name: c_2_pagedirect
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 43
  feature_group: 43
  feature_type: 3
  feature_name: c_2_pagedocpos
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 44
  feature_group: 44
  feature_type: 3
  feature_name: c_2_network
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 45
  feature_group: 45
  feature_type: 3
  feature_name: c_3_pagenum
  value_type: 3
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 46
  feature_group: 46
  feature_type: 2
  feature_name: d_st_5_tag
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 47
  feature_group: 47
  feature_type: 3
  feature_name: u_st_5_flavor
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 48
  feature_group: 48
  feature_type: 3
  feature_name: u_dy_5_applist
  value_type: 1
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 49
  feature_group: 49
  feature_type: 1
  feature_name: u_dy_5_readlist
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 50
  feature_group: 50
  feature_type: 1
  feature_name: u_dy_6_readlist3
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 51
  feature_group: 51
  feature_type: 1
  feature_name: u_dy_2_searchkeywordlist
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 52
  feature_group: 52
  feature_type: 3
  feature_name: u_dy_5_addshelflist
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 53
  feature_group: 53
  feature_type: 3
  feature_name: u_dy_5_sharelist
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 54
  feature_group: 54
  feature_type: 3
  feature_name: u_dy_3_addshelflist
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 55
  feature_group: 55
  feature_type: 3
  feature_name: u_dy_3_sharelist
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1

- slot: 56
  feature_group: 56
  feature_type: 3
  feature_name: u_dy_6_favocate5
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 手机型号
  status: 1
  is_dump: 1











