

- slot: 1
  feature_group: 1
  feature_type: 1
  feature_name: age
  value_type: 3
  disperse_num: 10
  value_max: 100
  value_min: 0
  decribe: age
  status: 1
  is_dump: 1
- slot: 2
  feature_group: 2
  feature_type: 1
  feature_name: workclass
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: workclass
  status: 1
  is_dump: 1
- slot: 3
  feature_group: 2
  feature_type: 1
  feature_name: fnlwgt
  value_type: 4
  disperse_num: 10
  value_max: 1490400
  value_min: 0
  decribe: fnlwgt
  status: 1
  is_dump: 1
- slot: 4
  feature_group: 4
  feature_type: 1
  feature_name: education
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: education
  status: 1
  is_dump: 1
- slot: 5
  feature_group: 5
  feature_type: 1
  feature_name: education-num
  value_type: 3
  disperse_num: 10
  value_max: 20
  value_min: 0
  decribe: education-num
  status: 1
  is_dump: 1
- slot: 6
  feature_group: 6
  feature_type: 1
  feature_name: marital-status
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: marital-status
  status: 1
  is_dump: 1
- slot: 7
  feature_group: 7
  feature_type: 1
  feature_name: occupation
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: occupation
  status: 1
  is_dump: 1
- slot: 8
  feature_group: 8
  feature_type: 1
  feature_name: relationship
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: relationship
  status: 1
  is_dump: 1
- slot: 9
  feature_group: 9
  feature_type: 1
  feature_name: race
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: race
  status: 1
  is_dump: 1
- slot: 10
  feature_group: 10
  feature_type: 1
  feature_name: sex
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: sex
  status: 1
  is_dump: 1
- slot: 11
  feature_group: 11
  feature_type: 1
  feature_name: capital-gain
  value_type: 4
  disperse_num: 10
  value_max: 100000
  value_min: 0
  decribe: capital-gain
  status: 1
  is_dump: 1
- slot: 12
  feature_group: 12
  feature_type: 1
  feature_name: capital-loss
  value_type: 3
  disperse_num: 10
  value_max: 5000
  value_min: 0
  decribe: capital-loss
  status: 1
  is_dump: 1
- slot: 13
  feature_group: 13
  feature_type: 1
  feature_name: hours-per-week
  value_type: 3
  disperse_num: 10
  value_max: 100
  value_min: 0
  decribe: hours-per-week
  status: 1
  is_dump: 1
- slot: 14
  feature_group: 14
  feature_type: 1
  feature_name: native-country
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: native-country
  status: 1
  is_dump: 1
