

- slot: 1
  feature_group: 1
  feature_type: 1
  feature_name: u_st_2_uid
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户id
  status: 1
  is_dump: 1
- slot: 2
  feature_group: 2
  feature_type: 1
  feature_name: u_st_2_gender
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户性别
  status: 1
  is_dump: 1
- slot: 3
  feature_group: 2
  feature_type: 1
  feature_name: u_st_3_age
  value_type: 3
  disperse_num: 10
  value_max: 100
  value_min: 0
  decribe: 用户年龄
  status: 1
  is_dump: 1
- slot: 4
  feature_group: 4
  feature_type: 1
  feature_name: u_st_2_occupation
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户职业
  status: 1
  is_dump: 1
- slot: 5
  feature_group: 5
  feature_type: 1
  feature_name: u_st_2_zip-code
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe: 用户压缩码
  status: 1
  is_dump: 1
- slot: 6
  feature_group: 6
  feature_type: 2
  feature_name: d_st_2_did
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe:
  status: 1
  is_dump: 1
- slot: 7
  feature_group: 7
  feature_type: 2
  feature_name: d_st_2_title
  value_type: 2
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe:
  status: 1
  is_dump: 1
- slot: 8
  feature_group: 8
  feature_type: 2
  feature_name: d_st_5_genres
  value_type: 5
  disperse_num: 0
  value_max: 0
  value_min: 0
  decribe:
  status: 1
  is_dump: 1
